Update hass.h - add missing  "hass_init_textField_info()" to avoid breaking ESP builds
ESP builds with "-Werror=implicit-function-declaration", so we get

 error: implicit declaration of function 'hass_init_textField_info';