Platforms.md WPA3 updates (#1754)
* Update drv_ir_new.cpp

* Update hass.h - add missing  "hass_init_textField_info()" to avoid breaking ESP builds 

ESP builds with "-Werror=implicit-function-declaration", so we get

 error: implicit declaration of function 'hass_init_textField_info';

* Update platforms.md - wpa3

* Update platforms.md

* revert ameba1 wpa3 to unknown

---------

Co-authored-by: MaxineMuster <146550015+MaxineMuster@users.noreply.github.com>