Implement LittleFS for LN882H - only first basic testing from WebApp … (#1191)
* Implement LittleFS for LN882H - only first basic testing from WebApp !!!!

- need to add littlefs-source to sdk/OpenLN882H/project/OpenBeken/CMakeLists.txt

Remarks:
I had to move the import part of LittleFS

in various cmd-source files to nearer to the top of the files

otherwise I had very strange (false!!!) compiler errors regarding
"conflicting types" for equal(!) typed prototypes and functions or even variables in .h and .c files

e.g.:

/OpenBK7231T_App/sdk/OpenLN882H/project/OpenBeken/app/src/cmnds/cmd_main.c:47:6: error: conflicting types for 'g_powersave'
   47 | bool g_powersave;
      |      ^~~~~~~~~~~
In file included from /OpenBK7231T_App/sdk/OpenLN882H/project/OpenBeken/app/src/cmnds/cmd_local.h:4,
                 from /OpenBK7231T_App/sdk/OpenLN882H/project/OpenBeken/app/src/cmnds/cmd_main.c:6:
/OpenBK7231T_App/sdk/OpenLN882H/project/OpenBeken/app/src/cmnds/cmd_public.h:33:13: note: previous declaration of 'g_powersave' was here
   33 | extern bool g_powersave;
      |             ^~~~~~~~~~~
/OpenBK7231T_App/sdk/OpenLN882H/project/OpenBeken/app/src/cmnds/cmd_main.c:47:6: error: conflicting types for 'g_powersave'
   47 | bool g_powersave;
      |      ^~~~~~~~~~~

Also I had to disable other drivers, or the OTA image would not be flashed (after rebbot old version was still present)
Is there a size limit to respect for OTA? the size was well below the shown OTA-size of 0xAA000 (696320k if I calculated correct)

* Moved "bool" from local int definition to stdbool.h
So I got rid of all those "conflicting types" errors.

Thanks to @giedriuslt for pointing this out!

This commit also includes a define of "ENABLE_TEST_COMMANDS" for the littlefs tests (lfs_test<n>).

* Restored all #defines to 1
Last image loaded without any problem

* Update cmd_main.c - temporarily removed one define to be able to sync to master

Changed 
#if (defined WINDOWS) || (defined PLATFORM_BEKEN) || (defined PLATFORM_BL602) || (defined PLATFORM_LN882H)
back to
#if (defined WINDOWS) || (defined PLATFORM_BEKEN) || (defined PLATFORM_BL602)

in src/cmnds/cmd_main.c

* Update cmd_main.c

Restored change in cmd_main.c after syncing

* Update user_main.c

Changed user_main.c to allow SVM_RunThreads() for LN882H with LittleFS

* Merged updated OpenLN882H

* Disable building test commands in obk_config.h

* Also "#define ENABLE_EXPAND_CONSTANT 1" to allow more advanced scripting

* Added LN882H to some more "#if defined" lines to allow scripting ...
Added BL602 in two lines missing this platform, too

---------

Co-authored-by: openshwprojects <85486843+openshwprojects@users.noreply.github.com>